<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>GameApp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\LearningOpenTK\LearningOpenTK\LearningOpenTK.csproj"/>
        <ProjectReference Include="..\VoxelWorldEngine\VoxelWorldEngine.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
        <PackageReference Include="OpenTK.Mathematics" Version="4.9.4" />
        <PackageReference Include="OpenTK.Windowing.Desktop" Version="4.9.4" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Assets\Shaders\chunk.frag">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Shaders\chunk.vert">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Textures\Stone.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Fonts\Pixel.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Fonts\Pixel.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Shaders\plain.frag">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Shaders\plain.vert">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Shaders\line.frag">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Shaders\line.vert">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Textures\Ui\ArrowLeft.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Textures\Ui\Cross.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Textures\Ui\Play.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Textures\Ui\Empty.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Textures\Ui\Plain.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Textures\Blocks\Stone.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="LowLevel\" />
    </ItemGroup>

</Project>
