<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Rider\LearningOpenTK\LearningOpenTK\LearningOpenTK.csproj" />
        <ProjectReference Include="..\VoxelWorldEngine\VoxelWorldEngine.csproj"/>
    </ItemGroup>

</Project>
